---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by brode.
--- DateTime: 10.02.2022 10:15
---

local _, E = ...

function E:HookLootFrame()
    for i = 1, 4 do
        E:HookLootItemFrame(_G["LootButton"..i], i)
    end
    for i = 1, 11 do
        local n = 1
        while true do
            local itemFrame = _G["ContainerFrame"..i.."Item"..n]
            if not itemFrame then
                break
            end
            E:HookContainerItemFrame(itemFrame)
            n = n + 1
        end

    end
end

function E:HookLootItemFrame(frame, index)
    frame:HookScript("OnClick", function()

        if (E:CanStartAuctionWithClick()) then
            local numLootItems = GetNumLootItems()
            local numLootToShow = LOOTFRAME_NUMBUTTONS;
            if ( numLootItems > LOOTFRAME_NUMBUTTONS ) then
                numLootToShow = numLootToShow - 1; -- make space for the page buttons
            end
            local slot = (numLootToShow * (LootFrame.page - 1)) + index;
            local texture, item, quantity, currencyID, quality, _, _, _, _ = GetLootSlotInfo(slot);
            if ( currencyID ) then
                item, texture, quantity, quality = CurrencyContainerUtil.GetCurrencyContainerInfo(currencyID, quantity, item, texture, quality);
            end

            local itemLink = GetLootSlotLink(slot)
            E:StartAuction(itemLink, quantity, frame)

        end
    end)
end


function E:HookContainerItemFrame(frame)
    frame:HookScript("OnClick", function(self)
        if (E:CanStartAuctionWithClick()) then
            texture, itemCount, locked, quality, readable, lootable, itemLink = GetContainerItemInfo(self:GetParent():GetID(), self:GetID());
            E:StartAuction(itemLink, itemCount, frame)
        end
    end)
end

