---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by brode.
--- DateTime: 07.02.2022 22:06
---

local _, E = ...

local A = E.EVENTS
local C = E.CORE

E.EVENT = {
    CHARACTERS_INFO = "CHARACTERS_INFO",
    CHARACTERS_INFO_REQUEST = "CHARACTERS_INFO_REQUEST",
}

function A:READY()
    E:SaveCharacterInfo()
    E:RequestCharactersInfo()
end

function A:GUILD_ROSTER_UPDATE()
    if C.firstLoad then
        E:SaveCharacterInfo()
    end
end

function A:CHARACTERS_INFO_REQUEST(sender)
    E:ShareCharactersInfo(sender)
end

function A:CHARACTERS_INFO(characters, sender)
    characters = { strsplit(",", characters) }
    RosterCharacters[sender] = characters
end

function A:UPDATE_GUILD_MEMBER(row, _, numMembers, fullName)
    E:RenderMainCharacterInfo(row, fullName)
end

function A:GUILD_FRAME_AFTER_UPDATE()
    local fullName, rank = GetGuildRosterInfo(GetGuildRosterSelection());
    local charData = E:GetGuildMemberCharactersData(fullName)
    local name, rankMain = E:GetMainCharacter(charData)
    if name and name ~= fullName then
        GuildMemberDetailName:SetText(format("%s (%s)", GuildMemberDetailName:GetText(), C:AddClassColorToName(name)))
        GuildMemberDetailRankText:SetText(format("%s %s", rank, C:colorize(format("(%s)", C:colorize(rankMain, C.COLOR.WHITE)), C.COLOR.NORMAL)))
    end
end

function A:GUILD_MEMBER_COUNT_CHANGED(_, online)
    for player, _ in pairs(online) do
        E:RequestCharactersInfoFrom(player)
    end
end

function A:CACHED_GUILD_DATA()
    local roster = {}
    for _, data in pairs(C.guildRoster) do
        table.insert(roster, data)
    end
    if #Bohemian_Characters > 0 then
        local left = E:CompareRosters(Bohemian_Characters, roster)
        local joined = E:CompareRosters(roster, Bohemian_Characters)
        if #left > 0 then
            local parsed = E:GetPrettyPlayers(left)
            E:Print("Players left the guild: " .. table.concat(parsed, ", "))
        end
        if #joined > 0 then
            local parsed = E:GetPrettyPlayers(joined)
            E:Print("Players joined the guild: " .. table.concat(parsed, ", "))
        end
    end

    Bohemian_Characters = roster
end