---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by brode.
--- DateTime: 07.02.2022 18:06
---
local AddonName, E = ...

E.NAME = AddonName

E.AVAILABLE_MODULES = {
    "Bohemian_Auction",
    "Bohemian_Characters",
    "Bohemian_DKP",
    "Bohemian_Log",
    "Bohemian_Professions",
    "Bohemian_Raid",
    "Bohemian_Talents",
    "Bohemian_ElvUI",
}

E.STRING = {
    DEBUG = '%s: %s',
    OUT_OF_DATE = "I am out of date. Please update me. "
}

E.COMMAND = {
    DEBUG = 'debug'
}

E.EVENT_SEPARATOR = "\011"
E.COMPRESSED_SEPARATOR = ";"

E.EVENT = {
    PAYLOAD_START_CONFIRM = "PAYLOAD_START_CONFIRM",
    PAYLOAD_START = "PAYLOAD_START",
    PAYLOAD_DONE = "PAYLOAD_DONE",
    VERSION_INFO = "VERSION_INFO",
    VERSION_INFO_REQUEST = "VERSION_INFO_REQUEST",
    WHISPER = "WHISPER",

    ONLINE_CHECK = "ONLINE_CHECK",
    ONLINE_CHECK_RESPONSE = "ONLINE_CHECK_RESPONSE",

    BROADCAST_START = "BROADCAST_START",
    STREAM_DATA = "STREAM_DATA",
    CACHED_GUILD_DATA = "CACHED_GUILD_DATA",
    CACHED_GUILD_MEMBER = "CACHED_GUILD_MEMBER",
    READY = "READY",
    GUILD_MEMBER_COUNT_CHANGED = "GUILD_MEMBER_COUNT_CHANGED",
}

E.COLOR = {
    RED = {r=1,g=0,b=0},
    DARKRED = {r=0.72,g=0,b=0},
    GRAY = {r=0.5,g=0.5,b=0.5},
    WHITE = {r=1,g=1,b=1},
    GREEN = {r=0,g=1,b=0},
    YELLOW = {r=1,g=1,b=0},
    NORMAL = {r=1,g=0.82,b=0},
    ADDON = {r=0.25,g=0.41,b=0.88},
    DISABLE = {r=0.5,g=0.5,b=0.5},
    TURQOISE = {r = 0.41, g = 0.80, b = 0.94}
}
