---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by brode.
--- DateTime: 18.07.2021 9:58
---
---
local _, E = ...

E.cpsQueue = {}
E.cps = 0
E.cpsOverhead = 40

CHUNK_HEAD_SIZE = 40

local cpsFrame = CreateFrame("Frame")
cpsFrame:SetScript("OnUpdate", function(_, elapsed)
    E.cps = math.max(E.cps - (BohemianConfig.cpsLimit * elapsed), 0)
    if #E.cpsQueue > 0 then
        local item = E.cpsQueue[1]
        if #item[1] <= E:GetCPSLimit() then
            E:SendAddonMessage(unpack(item))
            table.remove(E.cpsQueue, 1)
        end
    end
end)
function E:GetCPSLimit()
    return BohemianConfig.cpsLimit - E.cps
end

function E:CreatePayload(payloadType, chunkAmount, id, sender)
    if not self.chunks[id] then
        self.chunks[id] = {
            data = {},
            size = tonumber(chunkAmount),
            received = 0,
            type = payloadType,
            sender = sender
        }
        self:Debug("Payload slot created", id)
    else
        self:Debug("Payload ID exists", id)
    end
end

function E:StartBroadcastPayload(id)
    local chunks = self.chunksToSend[id]
    if not chunks then
        return
    end
    local sep = self.COMPRESSED_SEPARATOR..id

    for i, chunk in ipairs(chunks) do
        local sep2 = self.EVENT_SEPARATOR..i
        self:SendAddonMessage(sep..sep2..self.EVENT_SEPARATOR..chunk, "GUILD")
    end
    self.chunksToSend[id] = nil
end

function E:IsSyncInProgress()
    local n = 0
    for _, _ in ipairs(self.chunks) do
        n = n + 1
    end
    return n > 0
end
