---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by brode.
--- DateTime: 07.02.2022 17:59
---

local _, E = ...

function E:IsPlayerLootMaster()
    local _, masterLooterPartyID, _ = GetLootMethod()
    return masterLooterPartyID == 0
end

function E:GetPlayerName(useFullName)
    if useFullName then
        local fullName, realm = UnitFullName("player")
        if not fullName then
            return
        end
        return fullName.."-"..(realm or GetNormalizedRealmName())
    end
    return UnitName("player")
end

function E:GetClassFileName(name)
    local classFileName
    if self.guildRoster[name] then
        local _, _, _, _, _, _, _, _, _, _, classFileName2  = unpack(self.guildRoster[name])
        classFileName = classFileName2
    else
        local shortName = strsplit("-", name)
        local _, classFileName2, _ = UnitClass(shortName)
        classFileName = classFileName2
    end
    return classFileName
end

function E:GetClassColor(name)
    local classFileName = self:GetClassFileName(name)
    return RAID_CLASS_COLORS[classFileName]
end

function E:AddClassColorToName(name)
    if not name then
        return
    end
    local shortName = strsplit("-", name)
    local color = self:GetClassColor(name)
    if color then
        local escapeColor = format("|cff%02x%02x%02x", color.r*255, color.g*255, color.b*255)
        shortName = escapeColor..shortName.."|r"
    end
    return shortName
end

function E:IsPlayerOnline(name)
    local data = self.guildRoster[name or self:GetPlayerName(true)]
    if data then
        return select(9, unpack(data))
    end
end
