---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by brode.
--- DateTime: 07.02.2022 17:40
---
---
local _, E = ...


function E:roundWhole(num, l)
    return math.floor(num / l + 0.5) * l
end

local b = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/'

function E:encodeBase64(data)
    return ((data:gsub('.', function(x)
        local r,a='',x:byte()
        for i=8,1,-1 do r=r..(a%2^i-a%2^(i-1)>0 and '1' or '0') end
        return r;
    end)..'0000'):gsub('%d%d%d?%d?%d?%d?', function(x)
        if (#x < 6) then return '' end
        local c=0
        for i=1,6 do c=c+(x:sub(i,i)=='1' and 2^(6-i) or 0) end
        return b:sub(c+1,c+1)
    end)..({ '', '==', '=' })[#data%3+1])
end


function E:decodeBase64(data)
    data = string.gsub(data, '[^'..b..'=]', '')
    return (data:gsub('.', function(x)
        if (x == '=') then return '' end
        local r,f='',(b:find(x)-1)
        for i=6,1,-1 do r=r..(f%2^i-f%2^(i-1)>0 and '1' or '0') end
        return r;
    end):gsub('%d%d%d?%d?%d?%d?%d?%d?', function(x)
        if (#x ~= 8) then return '' end
        local c=0
        for i=1,8 do c=c+(x:sub(i,i)=='1' and 2^(8-i) or 0) end
        return string.char(c)
    end))
end

function E:display_time(time, formatString)
    local hours = floor(mod(time, 86400)/3600)
    local minutes = floor(mod(time,3600)/60)
    local seconds = floor(mod(time,60))
    return format(formatString or "%02d:%02d:%02d",hours,minutes,seconds)
end

function round(num, numDecimalPlaces)
    local mult = 10^(numDecimalPlaces or 0)
    return math.floor(num * mult + 0.5) / mult
end

function TryLoadAddOn(name)
    local loaded, reason = LoadAddOn(name)
    if not loaded then
        if reason == "DISABLED" then
            EnableAddOn(name, true) -- enable for all characters on the realm
            LoadAddOn(name)
        else
            local failed_msg = format("%s - %s", reason, _G["ADDON_"..reason])
            error(ADDON_LOAD_FAILED:format(name, failed_msg))
        end
    end
end
