---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by brode.
--- DateTime: 07.02.2022 22:06
---

local _, E = ...

local A = E.EVENTS
local C = E.CORE
E.EVENT = {
    STATS = "STATS",
    REQUEST_STATS = "REQUEST_STATS",
}

C:RegisterEvent('ACHIEVEMENT_EARNED')
C:RegisterEvent('PLAYER_PVP_KILLS_CHANGED')
C:RegisterEvent('ARENA_TEAM_UPDATE')
C:RegisterEvent('PVP_RATED_STATS_UPDATE')

function A:READY()
    E:RequestStats()
end

function A:GUILD_FRAME_BEFORE_UPDATE()
    E:UpdateSelectedListFrame()
end

function A:GUILD_FRAME_UPDATE()
    E:UpdateSelectedListFrame()
end

function A:GUILD_FRAME_AFTER_UPDATE()
    E:UpdateSelectedListFrame()
    if E.selectedList ~= 3 then
        return
    end
    local guildOffset = FauxScrollFrame_GetOffset(GuildListScrollFrame);
    local showOffline = GetGuildRosterShowOffline()
    E.members = {}
    for i = 1, #C.guildRosterIndexMap do
        --local guildIndex = guildOffset + i
        local member = C:GetGuildMemberByIndex(i)
        if member then
            local fullName, rank, rankIndex, level, class, zone, note, officernote, online, isAway, classFileName = unpack(member)
            if (not showOffline and online) or showOffline then
                local stats = Bohemian_Statistics.players[fullName] or {}
                E.members[i] = {
                    index = i,
                    name = fullName,
                    online = online,
                    classFileName = classFileName,
                    achievement = stats.achievement or 0,
                    hk = stats.hk or 0,
                    arena2v2 = stats.arena2v2 or 0,
                    arena3v3 = stats.arena3v3 or 0,
                    arena5v5 = stats.arena5v5 or 0,
                    rep = stats.rep or 0
                }
            end

        end

    end
    E:SortMembers()
    E:UpdateStatisticRows()
end

--function A:UPDATE_GUILD_MEMBER(row, i, numMembers, fullName, rank, rankIndex, level, class, zone, note, officerNote, online, isAway, classFileName)
--    E.members[row] = {
--        index = i,
--        name = fullName,
--        online = online,
--        classFileName = classFileName
--    }
--    local stats = Bohemian_Statistics[fullName]
--    if stats then
--        for k, v in pairs(stats) do
--            E.members[row][k] = v
--        end
--    end
--    print("Updated", row, fullName)
--    if row == GUILDMEMBERS_TO_DISPLAY then
--        E:UpdateStatisticRows()
--    end
--end


function A:STATS(achievementPoints, hk, rat2v2, rat3v3, rat5v5, rep, sender)
    Bohemian_Statistics.players[sender] = {
        achievement = tonumber(achievementPoints),
        hk = tonumber(hk),
        arena2v2 = tonumber(rat2v2),
        arena3v3 = tonumber(rat3v3),
        arena5v5 = tonumber(rat5v5),
        rep = tonumber(rep)
    }
end

function A:REQUEST_STATS(sender)
    E:ShareStats(sender)
end

function A:ACHIEVEMENT_EARNED()
    E:ShareStats()
end

function A:PLAYER_PVP_KILLS_CHANGED()
    E:ShareStats()
end

function A:ARENA_TEAM_UPDATE()
    E:ShareStats()
end

function A:PVP_RATED_STATS_UPDATE()
    E:ShareStats()
end

function A:REPUTATION_CHANGED(playerName)
    if playerName ~= C:GetPlayerName(true) then
        return
    end
    E:ShareStats()
end