---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by brode.
--- DateTime: 07.02.2022 19:08
---
---
---
local AddonName, E = ...

Bohemian.RegisterModule(AddonName, E, function()
    E:AddToggleButton()
    E:CreateStatisticsFrame()
    RequestRatedInfo()
    E:RefreshOnChange()

end)

local C = E.CORE

if not Bohemian_Statistics then
    Bohemian_Statistics = {
        selectedList = 1,
        players = {},
        sortType = "name",
        desc = false,
    }
end
E.refreshIn = 0
E.members = {}

function E:RequestStats()
    C:SendEvent("GUILD", E.EVENT.REQUEST_STATS)
end

function E:RefreshOnChange()
    C:AddToUpdateQueue(function(id, elapsed)
        if E.refreshIn <= 0 and E.shouldRefresh then
            E.shouldRefresh = false
            E:UpdateMemberStats()
        elseif E.refreshIn > 0 then
            E.refreshIn = E.refreshIn - elapsed
        end
    end)
end

function E:ShareStats(sendTo)
    if not E.statsLoaded then
        return
    end
    local points = GetTotalAchievementPoints()
    local honorableKills, dishonorableKills, highestRank = GetPVPLifetimeStats()
    local payload = {
        [1] = points,
        [2] = honorableKills,
    }
    for i = 1, 3 do
        local rating = GetPersonalRatedInfo(i)
        table.insert(payload, rating)
    end
    local module = C:GetModule("Bohemian_Reputation")
    local rep = 0
    if module then
        rep = module:GetPlayerReputation(C:GetPlayerName(true)).total or 0
    end
    table.insert(payload, rep)
    if sendTo then
        C:SendEventTo(sendTo, E.EVENT.STATS, unpack(payload))
    else
        C:SendEvent("GUILD", E.EVENT.STATS, unpack(payload))
    end

end

function E:SortMembers()
    table.sort(E.members, function(a,b)
        if Bohemian_Statistics.desc then
            return a[Bohemian_Statistics.sortType] < b[Bohemian_Statistics.sortType]
        else
            return a[Bohemian_Statistics.sortType] > b[Bohemian_Statistics.sortType]
        end
    end)
end

function E:UpdateMemberStats()
    local showOffline = GetGuildRosterShowOffline()
    E.members = {}
    for i = 1, #C.guildRosterIndexMap do
        local member = C:GetGuildMemberByIndex(i)
        if member then
            local fullName, rank, rankIndex, level, class, zone, note, officernote, online, isAway, classFileName = unpack(member)
            if (not showOffline and online) or showOffline then
                local stats = Bohemian_Statistics.players[fullName] or {}
                E.members[i] = {
                    index = i,
                    name = fullName,
                    online = online,
                    classFileName = classFileName,
                    achievement = stats.achievement or 0,
                    hk = stats.hk or 0,
                    arena2v2 = stats.arena2v2 or 0,
                    arena3v3 = stats.arena3v3 or 0,
                    arena5v5 = stats.arena5v5 or 0,
                    rep = stats.rep or 0
                }
            end

        end

    end
    E:SortMembers()
    E:UpdateStatisticRows()
end