---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by brode.
--- DateTime: 07.02.2022 19:08
---
---
---
local AddonName, E = ...

Bohemian.RegisterModule(AddonName, E, function()
    E:AddToggleButton()
    E:CreateStatisticsFrame()
end)

local C = E.CORE

if not Bohemian_Statistics then
    Bohemian_Statistics = {
        selectedList = 1,
        players = {},
        sortType = "name",
        desc = false,
    }
end

E.members = {}

function E:RequestStats()
    C:SendEvent("GUILD", E.EVENT.REQUEST_STATS)
end

function E:ShareStats(sendTo)
    local points = GetTotalAchievementPoints()
    local honorableKills, dishonorableKills, highestRank = GetPVPLifetimeStats()
    local payload = {
        [1] = points,
        [2] = honorableKills,
    }
    for i = 1, 3 do
        local rating = GetPersonalRatedInfo(i)
        table.insert(payload, rating)
    end
    local module = C:GetModule("Bohemian_Reputation")
    local rep = 0
    if module then
        rep = module:GetPlayerReputation(C:GetPlayerName(true)).total or 0
    end
    table.insert(payload, rep)
    --print("SHARING STATS", sendTo)
    if sendTo then
        C:SendEventTo(sendTo, E.EVENT.STATS, unpack(payload))
    else
        C:SendEvent("GUILD", E.EVENT.STATS, unpack(payload))
    end

end

function E:SortMembers()
    table.sort(E.members, function(a,b)
        if Bohemian_Statistics.desc then
            return a[Bohemian_Statistics.sortType] < b[Bohemian_Statistics.sortType]
        else
            return a[Bohemian_Statistics.sortType] > b[Bohemian_Statistics.sortType]
        end
    end)
end