---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by brode.
--- DateTime: 07.02.2022 19:08
---
---
---
local AddonName, E = ...

Bohemian.RegisterModule(AddonName, E, function()

end)

local C = E.CORE

if not Bohemian_Achievements then
    Bohemian_Achievements = {}
end
