---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by brode.
--- DateTime: 07.02.2022 23:44
---

local _, E = ...
local C = E.CORE
LAST_COLUMN_HEADER_INDEX = 5
PROFESSION_AMOUNT = 6
GUILD_FRAME_COLUMN_WIDTH_PROFESSIONS = 101

function E:CreateGuildFrameProfessionsColumnHeader()
    local f = C:AddGuildColumnHeader("GuildFrameColumnHeader6", GUILD_FRAME_COLUMN_WIDTH_PROFESSIONS, LAST_COLUMN_HEADER_INDEX, "Profession")
    f:SetText("Professions")
    local callback = function()
        GuildCraftListFrame:Show()
        E:PositionGuildCraftFrame()
        E:RenderCraftsMulti()
    end
    f:SetScript("OnMouseDown", callback)
    local book = C:CreateFrame("Button", "$parentBook", f)
    book:SetSize(17, 17)
    book:SetPoint("RIGHT", f, -5, -2)
    book:SetHighlightTexture("Interface\\QuestFrame\\UI-QuestTitleHighlight")
    book:RegisterForClicks("LeftButtonDown", "RightButtonDown")
    book:SetScript("OnClick", callback)
    local texture = book:CreateTexture(nil, "BACKGROUND")
    texture:SetAllPoints(true)
    texture:SetTexture(133741)
    E:CreateGuildFrameProfessionColumns()
end

function E:CreateGuildFrameProfessionColumns()
    for i=1, GUILDMEMBERS_TO_DISPLAY do
        local _, _, _, _, _, _, _, officerNote, _, _ = GetGuildRosterInfo(i)

        self:CreateGuildFrameProfessionButton("GuildFrameButton"..i.."Profession", 15, _G["GuildFrameButton"..i.."Profession"], "LEFT", 0, 0)
    end
end

function E:PositionGuildCraftFrame()
    GuildCraftFrame:ClearAllPoints()
    local point, relativeTo, relativePoint, xOfs, yOfs = FriendsFrame:GetPoint()
    GuildCraftListFrame:ClearAllPoints(true)
    if GuildCraftListFrame:IsVisible() then
        if FriendsFrame:IsVisible() then
            GuildCraftListFrame:SetPoint("TOPLEFT", FriendsFrame, "TOPRIGHT", 0, GuildCraftFrame.detachedY)
        else
            GuildCraftListFrame:SetPoint("TOPLEFT", UIParent, xOfs, yOfs)
        end

        GuildCraftFrame:SetPoint("TOPLEFT", GuildCraftListFrame, "TOPRIGHT", GuildCraftFrame.attachedX, 0)
    else
        if FriendsFrame:IsVisible() then
            GuildCraftFrame:SetPoint("TOPLEFT", FriendsFrame, "TOPRIGHT", 0, GuildCraftFrame.detachedY)
        else
            GuildCraftFrame:SetPoint("TOPLEFT", UIParent, xOfs, yOfs)
        end

    end
end

function E:CreateGuildFrameProfessionButton(prefixName, size, relativeTo, ...)
    local prevProf
    local profFrameContainer = C:CreateFrame("Frame", prefixName.."FrameContainer", relativeTo)
    profFrameContainer:SetPoint(...)
    profFrameContainer:SetSize(1, size)
    for j = 1, PROFESSION_AMOUNT do
        local profFrame = C:CreateFrame("Frame", prefixName.."Frame"..j, profFrameContainer)
        profFrame:SetSize(size, size)
        profFrame:SetFrameStrata("HIGH")
        profFrame:SetScript("OnEnter", function(self)
            if self.tooltip then
                GameTooltip:SetOwner(self, "ANCHOR_TOP");
                GameTooltip:SetText(self.tooltip);
                GameTooltip:Show();
            end
        end)
        profFrame:SetScript("OnLeave", function()
            GameTooltip:Hide();
        end)
        profFrame:SetScript("OnMouseDown", function(self)
            local guildCrafts = E:GetGuildCrafts()
            if guildCrafts[self.playerName] then
                local crafts = guildCrafts[self.playerName][self.profession.name]
                if crafts then
                    E:RenderCrafts(self.playerName, self.profession, crafts)
                    E:ScrollToSelectedCraft()
                end
            end
        end)
        if not prevProf then
            profFrame:SetPoint("TOPLEFT", 0, 0)
        else
            local padding = 0
            if j == 5 then
                padding = 4
            end
            profFrame:SetPoint("LEFT", prevProf, "RIGHT", padding, 0)
        end

        font = profFrame:CreateFontString(prefixName.."Skill"..j,"OVERLAY", "GameFontNormalSmall")
        font:SetJustifyH("CENTER")
        font:SetAllPoints(profFrame)
        font:SetText("")
        font:SetFont("Fonts\\FRIZQT__.TTF", 11, "OUTLINE")

        local prof = profFrame:CreateTexture("$parentProf", "ARTWORK")
        prof:SetAllPoints(profFrame)
        prof.parent = profFrame
        profFrame.font = font
        prevProf = profFrame
    end
end

function E:AddLFGFrameButton()
    local profButton = C:CreateFrame("CheckButton", "GuildFrameProfButton", GuildFrameLFGFrame, "UICheckButtonTemplate")
    profButton:SetSize(20, 20)
    profButton:SetChecked(Bohemian_ProfessionsConfig.showProfessions)
    profButton:SetScript("OnClick", function(self)
        Bohemian_ProfessionsConfig.showProfessions = self:GetChecked()
         E:RenderColumns()
    end)
    C:AddLFGButton(profButton:GetName(), 2, 70)
    local font = profButton:CreateFontString("$parentText","ARTWORK", "GameFontHighlightSmall")
    font:SetText("Professions")
    font:SetPoint("RIGHT", profButton, "LEFT", -3, 1)
end


function E:RenderColumns()
    if Bohemian_ProfessionsConfig.showProfessions then
        GuildFrameColumnHeader6:Show()
    else
        GuildFrameColumnHeader6:Hide()
    end
    C:GuildStatus_UpdateHook()
end

function E:RenderProfessions(frameName, playerName, professions, showSkill)
    for i = 1, PROFESSION_AMOUNT do
        local detailFrame = _G[format(frameName, i)]
        self:HideProfessionFrame(detailFrame)
    end
    for i = 1, #professions do
        local detailFrame = _G[format(frameName, i)]
        local name = professions[i].name
        if E.PROFESSIONS[name] then
            local tooltip = name
            local isSecondary = E.SECONDARY_PROFESSIONS[name]
            if isSecondary then
                detailFrame = _G[format(frameName, E.PROFESSIONS[name])]
            end
            if detailFrame then
                if showSkill then
                    detailFrame.parent.font:SetText(professions[i].rank)
                elseif professions[i].rank then
                    tooltip = tooltip.." - "..professions[i].rank
                end
                detailFrame.parent.tooltip = tooltip
                detailFrame.parent.playerName = playerName
                detailFrame.parent.profession = professions[i]
                local alpha = 0.5
                local craftHistory = self:GetPlayerCraftHistory(playerName)
                if craftHistory and craftHistory[name] then
                    alpha = 1
                end
                detailFrame:SetAlpha(alpha)
                detailFrame:SetTexture(self:GetProfessionIcon(professions[i]))
                detailFrame.parent:Show()
            end
        end
    end
end

function E:HideProfessionFrame(frame)
    frame.parent.tooltip = nil
    frame.parent.font:SetText("")
    frame:SetTexture(nil)
    frame.parent:Hide()
end


function E:AdjustDetailFrame()
    self:CreateGuildFrameProfessionButton("DetailFrameProf", 30, GuildMemberDetailFrame, "BOTTOMLEFT", GuildMemberDetailFrame, "BOTTOMLEFT", 14, 38)
end

function E:UpdateDetailFrame()
    local fullName, _, _, _, _, _, _, _, _ = GetGuildRosterInfo(GetGuildRosterSelection());
    --print("WTF", GuildMemberOfficerNoteBackground:IsVisible())
    --local relativeTo
    --if GuildMemberOfficerNoteBackground:IsVisible() then
    --    relativeTo = GuildMemberOfficerNoteBackground
    --else
    --   relativeTo = GuildMemberNoteBackground
    --end
    --print("RELATIVE TO", relativeTo:GetName(), relativeTo:IsVisible())
    ----DetailFrameProfFrameContainer:ClearAllPoints(true)
    ----DetailFrameProfFrameContainer:SetPoint("TOPLEFT", GuildMemberNoteBackground, "BOTTOMLEFT", 0, -6)
    if ( GetGuildRosterSelection() > 0 ) then
        local professions = self:GetPlayerProfessions(fullName)
        if #professions > 0 then
            if not E.DetailFrameHasProfessions then
                C:IncreaseDetailFrameHeight(38)
            end
            E.DetailFrameHasProfessions = true
        else
            if E.DetailFrameHasProfessions then
                C:IncreaseDetailFrameHeight(-38)
            end
            E.DetailFrameHasProfessions = false
        end
        self:RenderProfessions("DetailFrameProfFrame%dProf", fullName, professions, true)
    end
end

