---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by brode.
--- DateTime: 10.02.2022 13:25
---

local _, E = ...

local C = E.CORE

function E:HookLootFrame()
    local fn = ElvUI[1].Bags.ConstructContainerButton
    ElvUI[1].Bags.ConstructContainerButton = function(...)
        local frame = fn(...)
        local module = C:GetModule("Bohemian_Auction")
        if module then
            module:HookContainerItemFrame(frame)
        end
        return frame
    end
end

function E:HookExistingBagFrames()
    local module = C:GetModule("Bohemian_Auction")
    if module then
        for _, bagFrame in next, ElvUI[1].Bags.BagFrames do
            for _, bagID in ipairs(bagFrame.BagIDs) do
                for slotID = 1, GetContainerNumSlots(bagID) do
                    local button = bagFrame.Bags[bagID] and bagFrame.Bags[bagID][slotID]
                    if button then
                        module:HookContainerItemFrame(button)
                    end
                end
            end
        end
    end
end

function E:HookLootItemFrameElvUI(frame, index)
    frame:HookScript("OnClick", function()
        local module = C:GetModule("Bohemian_Auction")
        if module then
            if (module:CanStartAuctionWithClick()) then
                local texture, item, quantity, currencyID, quality, _, _, _, _ = GetLootSlotInfo(index);
                if ( currencyID ) then
                    item, texture, quantity, quality = CurrencyContainerUtil.GetCurrencyContainerInfo(currencyID, quantity, item, texture, quality);
                end

                local itemLink = GetLootSlotLink(index)
                module:StartAuction(itemLink, quantity, frame.iconFrame)
            end
        end
    end)
end
