---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by brode.
--- DateTime: 07.02.2022 19:13
---

local _, E = ...

E.lastOnlineMembers = 0
E.onlineChecks = {}

Bohemian_CoreConfig = {}
