---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by brode.
--- DateTime: 07.02.2022 17:47
---

local _, E = ...

function E:colorize(text, color)
    local escapeColor = format("|cff%02x%02x%02x", color.r*255, color.g*255, color.b*255)
    return escapeColor..text.."|r"
end

function E:splitStringByChunks(text, size)
    local s = {}
    for i=1, #text, size do
        s[#s+1] = text:sub(i,i+size - 1)
    end
    return s
end

function E:split(s, delimiter)
    result = {};
    for match in (s..delimiter):gmatch("(.-)"..delimiter) do
        table.insert(result, match);
    end
    return result;
end

function E:isDigit(value)
    value = tonumber(value)
    if value then
        return true
    end
    return false
end

function E:Debug(...)
    if not Bohemian_CoreConfig.debug then
        return
    end
    self:debugMessage(self.NAME, ...)
end


function E:Print(...)
    self:debugMessage(self.NAME, ...)
end

function E:Error(message)
    print(string.format(self.STRING.DEBUG, self:colorize(self.NAME, self.COLOR.RED), message))
end

function E:dump(o)
    if type(o) == 'table' then
        local s = '{ '
        for k,v in pairs(o) do
            if type(k) ~= 'number' then k = '"'..k..'"' end
            s = s .. '['..k..'] = ' .. self:dump(v) .. ','
        end
        return s .. '} '
    else
        return tostring(o)
    end
end

function E:debugMessage(name, ...)
    str = ''
    if type(...) == 'table' then
        str = self:dump(...)
    else
        for _,v in pairs({...}) do
            str = str .. tostring(v) .. ' '
        end
    end
    print(string.format(self.STRING.DEBUG, self:colorize(name, self.COLOR.ADDON), str))
end

local random = math.random
function E:uuid()
    local template ='xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'
    return string.gsub(template, '[xy]', function (c)
        local v = (c == 'x') and random(0, 0xf) or random(8, 0xb)
        return string.format('%x', v)
    end)
end
