---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by brode.
--- DateTime: 11.02.2022 9:36
---

local _, E = ...


function E:InitialSync()
    E.playersForSync = {}
    local members= GetNumGuildMembers();
    local count = 0
    for i = 1, members do
        local fullName, rank, rankIndex, level, class, zone, note, officernote, online, isAway, classFileName = GetGuildRosterInfo(i);
        if online and fullName ~= E:GetPlayerName(true) then
            E.playersForSync[fullName] = false
            count = count + 1
        end
    end
    if count > 0 then
        E:Debug("Initial sync initialized...")
        self.isInitialSyncActive = true
        E:SendEvent("GUILD", E.EVENT.ONLINE_CHECK)
    else
        E:Debug("Alone. Not syncing.")
        E:FinishSyncing()
    end
    C_Timer.After(5, function()
        E:FinishSyncing()
    end)
end

function E:FinishSyncing()
    if not E.syncFinished then
        E:ProcessQueue()
        E.syncFinished = true
        E:OnEvent("SYNC_READY")
        E:OnEvent("SYNC_DONE")
        E:Debug("Initial sync finished.")
    end
end

function E:ProcessPlayersForSync(playersForSync)
    local tmp = {}
    for _, item in pairs(playersForSync) do
        tmp[#tmp + 1] = item
    end
    if #tmp == 0 then
        return {}
    end
    table.sort(tmp, function (a, b) return a.onlineSince < b.onlineSince end)
    local playersToSyncFrom = {}
    local mainSource = false
    for _, member in ipairs(tmp) do
        if not mainSource and E.onlineSince - member.onlineSince > 300 then
            playersToSyncFrom[#playersToSyncFrom + 1] = member
            mainSource = true
        elseif E.onlineSince - member.onlineSince <= 300 then
            playersToSyncFrom[#playersToSyncFrom + 1] = member
        end
    end
    return playersToSyncFrom
end
