---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by brode.
--- DateTime: 07.02.2022 22:06
---

local _, E = ...

local A = E.EVENTS
local C = E.CORE

E.EVENT = {
    REPUTATION_CHANGED = "REPUTATION_CHANGED",
}

function A:READY()
    E:ShareAllPlayersReputation()
end

function A:REPUTATION_CHANGED(playerName, value, sender)
    E:SetReputation(playerName, tonumber(value), sender)
    A:GUILD_FRAME_AFTER_UPDATE()
end

function A:GUILD_FRAME_AFTER_UPDATE()
    E:UpdateDetailFrame()
end