---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by brode.
--- DateTime: 07.02.2022 19:08
---
---

local AddonName, E = ...

Bohemian.RegisterModule(AddonName, E, function()
    E:AddReputationButtons()
end)

local C = E.CORE

if not Bohemian_Reputation then
    Bohemian_Reputation = {
        shared = {},
        personal = {},
        id = C:uuid()
    }
end

function E:SetReputation(playerName, value, sender)
    if not Bohemian_Reputation.shared[playerName] then
        Bohemian_Reputation.shared[playerName] = {
            total = 0,
            players = {}
        }
    end
    if Bohemian_Reputation.shared[playerName].players[sender] then
        Bohemian_Reputation.shared[playerName].total = Bohemian_Reputation.shared[playerName].total - Bohemian_Reputation.shared[playerName].players[sender]
    end
    Bohemian_Reputation.shared[playerName].players[sender] = value
    Bohemian_Reputation.shared[playerName].total = Bohemian_Reputation.shared[playerName].total + value
end

function E:SetPositiveReputation(playerName)
    E:SetReputation(playerName, 1, Bohemian_Reputation.id)
end

function E:SetNegativeReputation(playerName)
    E:SetReputation(playerName, -1, Bohemian_Reputation.id)
end

function E:SharePlayerReputation(playerName, value)
    C:SendPriorityEvent("GUILD", E.EVENT.REPUTATION_CHANGED, playerName, value, Bohemian_Reputation.id)
    Bohemian_Reputation.personal[playerName] = value
end

function E:ShareCurrentPlayerReputation(value)
    local fullName = GetGuildRosterInfo(GetGuildRosterSelection());
    E:SharePlayerReputation(fullName, value)
end

function E:GetCurrentPlayerReputation()
    local fullName = GetGuildRosterInfo(GetGuildRosterSelection());
    return E:GetPlayerReputation(fullName)
end

function E:GetPlayerReputation(fullName)
    return Bohemian_Reputation.shared[fullName] or {}
end

function E:IsPlayerAlreadySet(playerName)
    return E:GetPlayerReputationFromMe(playerName) ~= nil
end

function E:GetPlayerReputationFromMe(playerName)
    if not Bohemian_Reputation.personal[playerName] then
        return
    end
    return Bohemian_Reputation.personal[playerName]
end

function E:GetCurrentPlayerReputationFromMe()
    local fullName = GetGuildRosterInfo(GetGuildRosterSelection());
    return E:GetPlayerReputationFromMe(fullName) or 0
end

function E:ShareAllPlayersReputation()
    local temp = {}
    for playerName, rep in pairs(Bohemian_Reputation.personal) do
        table.insert(temp, { playerName, rep })
    end
    local i = 1
    C:AddToUpdateQueue(function(id)
        if i > #temp then
            C:RemoveFromUpdateQueue(id)
            return
        end
        C:SendEvent("GUILD", E.EVENT.REPUTATION_CHANGED, temp[i][1], temp[i][2], Bohemian_Reputation.id)
        i = i + 1
    end)
end

function E:GetMyCharacters()
    return C:GetModule("Bohemian_Characters"):GetCharacters()
end

function E:IsMyCharacter()
    local fullName = GetGuildRosterInfo(GetGuildRosterSelection());
    local characters = E:GetMyCharacters()
    if not characters then
        return false
    end
    return characters[fullName] ~= nil
end