---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by brode.
--- DateTime: 09.02.2022 15:52
---
local _, E = ...

local C = E.CORE

function E:AddReputationButtons()
    local iconSize = 16

    local buttonRepMinus = C:CreateFrame("BUTTON", "$parentReputationMinus", GuildMemberDetailFrame)
    buttonRepMinus:SetPoint("TOPRIGHT", -35, -34)
    buttonRepMinus:SetSize(iconSize, iconSize)
    local texture = buttonRepMinus:CreateTexture(nil, "BACKGROUND")
    texture:SetTexture(135768)
    texture:SetAllPoints(true)
    buttonRepMinus:SetScript("OnClick", function()
        local repFromMe = E:GetCurrentPlayerReputationFromMe()
        E:ShareCurrentPlayerReputation(repFromMe < 0 and 0 or -1)
    end)

    local buttonRepPlus = C:CreateFrame("BUTTON", "$parentReputationPlus", GuildMemberDetailFrame)
    buttonRepPlus:SetPoint("LEFT", buttonRepMinus, "RIGHT", 4, 0)
    buttonRepPlus:SetSize(iconSize, iconSize)
    local texture2 = buttonRepPlus:CreateTexture(nil, "BACKGROUND")
    texture2:SetTexture(135769)
    texture2:SetAllPoints(true)

    buttonRepPlus:SetScript("OnClick", function()
        local repFromMe = E:GetCurrentPlayerReputationFromMe()
        E:ShareCurrentPlayerReputation(repFromMe > 0 and 0 or 1)
    end)

    local repInfo = C:CreateFrame("Frame", "$parentReputationInfo", GuildMemberDetailFrame)
    repInfo:SetPoint("RIGHT", buttonRepMinus, "LEFT", -5, 0)
    repInfo:SetSize(30, 20)

    local font = repInfo:CreateFontString("$parentText", "ARTWORK", "GameFontGreen")
    font:SetJustifyH("RIGHT")
    font:SetSize(30, 14)
    font:SetPoint("LEFT", repInfo)
    font:SetText("-")
end

function E:UpdateDetailFrame()
    local playerRep = E:GetCurrentPlayerReputation().total or 0
    GuildMemberDetailFrameReputationInfoText:SetText(playerRep)
    if playerRep > 0 then
        GuildMemberDetailFrameReputationInfoText:SetTextColor(0, 1, 0)
    elseif playerRep < 0 then
        GuildMemberDetailFrameReputationInfoText:SetTextColor(1.0, 0.1, 0.1)
    else
        GuildMemberDetailFrameReputationInfoText:SetTextColor(1.0, 0.82, 0)
    end
    if E:IsMyCharacter() then
        GuildMemberDetailFrameReputationMinus:SetAlpha(0.3)
        GuildMemberDetailFrameReputationPlus:SetAlpha(0.3)
        GuildMemberDetailFrameReputationMinus:Disable()
        GuildMemberDetailFrameReputationPlus:Disable()
    else
        GuildMemberDetailFrameReputationMinus:Enable()
        GuildMemberDetailFrameReputationPlus:Enable()
        local repFromMe = E:GetCurrentPlayerReputationFromMe()
        if repFromMe > 0 then
            GuildMemberDetailFrameReputationPlus:SetAlpha(1)
            GuildMemberDetailFrameReputationMinus:SetAlpha(0.3)
        elseif repFromMe < 0 then
            GuildMemberDetailFrameReputationMinus:SetAlpha(1)
            GuildMemberDetailFrameReputationPlus:SetAlpha(0.3)
        else
            GuildMemberDetailFrameReputationMinus:SetAlpha(1)
            GuildMemberDetailFrameReputationPlus:SetAlpha(1)
        end
    end

end
