---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by brode.
--- DateTime: 12.02.2022 11:20
---
local _, E = ...
local A = E.EVENTS

function A:COMBAT_LOG_EVENT_UNFILTERED(...)
    local timestamp, subevent, _, sourceGUID, sourceName, sourceFlags, sourceRaidFlags, destGUID, destName, destFlags, raidFlags, type = CombatLogGetCurrentEventInfo()
    --print(...)
    --print(CombatLogGetCurrentEventInfo())
    --print(_, _, prefix, suffix, type)
    if not IsInRaid() or not UnitIsGroupLeader("player") then
        return
    end


    if Bohemian_RaidConfig.announceParry then
        local _, subevent, _, _, sourceName, _, _, _, destName, _, _, type = CombatLogGetCurrentEventInfo()
        if subevent then
            local _, _, _, suffix = string.find (subevent, "(.-)_(.+)")
            if (suffix == "MISSED") then
                if (type == "PARRY") then
                    if E.raidMembers[sourceName] then
                        SendChatMessage(format("%s was parried by %s.", sourceName, destName), "RAID")
                    end

                end
            end
        end
    end

    if Bohemian_RaidConfig.announceMD then
        local _, subevent, _, _, sourceName, _, _, _, destName, _, _, _, spellName = CombatLogGetCurrentEventInfo()
        if subevent == "SPELL_CAST_SUCCESS" then
            if spellName == "Misdirection" then
                if E.raidMembers[sourceName] then
                    SendChatMessage(format("%s is misdirecting to %s.", sourceName, destName), "RAID")
                end
            end
        end
    end
end

function A:GROUP_ROSTER_UPDATE()
    E:CacheRaid()
end

function A:READY()
    SetCVar("cameraDistanceMaxZoomFactor", 4.0)
    SetCVar("nameplateMaxDistance", 41)
end
