---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by brode.
--- DateTime: 09.02.2022 18:31
---

local AddonName, E = ...
Bohemian_RaidConfig = {}
E.raidMembers = {}

Bohemian.RegisterModule(AddonName, E, function()
    Bohemian_RaidConfig.announceParry = Bohemian_RaidConfig.announceParry == nil and true or Bohemian_RaidConfig.announceParry
    Bohemian_RaidConfig.announceMD = Bohemian_RaidConfig.announceMD == nil and true or Bohemian_RaidConfig.announceMD
    E:AddConfigFrames(E.CORE:CreateModuleInterfaceConfig("Raid"))
end)


function E:CacheRaid()
    local members = GetNumGroupMembers();
    local realmName = GetNormalizedRealmName()
    local newRaidMembers = {}
    for i = 1, members do
        local name = GetRaidRosterInfo(i)
        if name then
            name, realm = UnitFullName(name)
            if not realm or #realm <= 0 then
                realm = realmName
            end
            local fullName = name.."-"..realm
            newRaidMembers[name] = {name = name, realm = realm, fullName = fullName}
        end
    end
    E.raidMembers = newRaidMembers
end

