---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by brode.
--- DateTime: 12.02.2022 12:20
---
local _, E = ...
local C = E.CORE

function E:AddConfigFrames(f)
    local toggleParry = C:CreateFrame("CheckButton", "$parentAnnounceParry", f, "UICheckButtonTemplate");
    toggleParry:SetSize(22,22)
    toggleParry:SetPoint("TOPLEFT", f, "TOPLEFT", 230, -22)
    toggleParry:SetChecked(Bohemian_RaidConfig.announceParry)

    font = toggleParry:CreateFontString("$parentText","ARTWORK", "GameFontNormal")
    font:SetJustifyH("LEFT")
    font:SetSize(200, 14)
    font:SetPoint("RIGHT", toggleParry, "LEFT", 0, 0)
    font:SetText("Announce parry")

    local toggleMD = C:CreateFrame("CheckButton", "$parentAnnounceMD", f, "UICheckButtonTemplate");
    toggleMD:SetSize(22,22)
    toggleMD:SetPoint("TOPLEFT", toggleParry, "BOTTOMLEFT", 0, 0)
    toggleMD:SetChecked(Bohemian_RaidConfig.announceMD)

    font = toggleMD:CreateFontString("$parentText","ARTWORK", "GameFontNormal")
    font:SetJustifyH("LEFT")
    font:SetSize(200, 14)
    font:SetPoint("RIGHT", toggleMD, "LEFT", 0, 0)
    font:SetText("Announce Misdirection")
end
