---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by brode.
--- DateTime: 07.02.2022 18:09
---

local _, E = ...

E.TALENTS = {
    DRUID = {
        Balance = 136096,
        FeralCombat = 132276,
        Restoration = 136041,
    },
    HUNTER = {
        BeastMastery = 132164,
        Marksmanship = 132222,
        Survival = 132215,
    },
    MAGE = {
        Arcane = 135932,
        Fire = 135812,
        Frost = 135846,
    },
    PALADIN = {
        Holy = 135920,
        Protection = 135893,
        Retribution = 135873,
    },
    PRIEST = {
        Discipline = 135987,
        Holy = 135920,
        Shadow = 136207,
    },
    ROGUE = {
        Assassination = 132292,
        Combat = 132090,
        Subtlety = 132320,
    },
    SHAMAN = {
        Elemental = 136048,
        Enhancement = 136051,
        Restoration = 136052,
    },
    WARLOCK = {
        Affliction = 136145,
        Demonology = 136172,
        Destruction = 136186,
    },
    WARRIOR = {
        Arms = 132292,
        Fury = 132347,
        Protection = 134952,
    },
    DEATHKNIGHT = {
        Blood = 135770,
        Frost = 135773,
        Unholy = 135775,
    },
}
