---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by brode.
--- DateTime: 07.02.2022 22:56
---

local _, E = ...
local A = E.EVENTS
local C = E.CORE

C:RegisterEvent('CHARACTER_POINTS_CHANGED')

function A:READY()
    E:RequestTalentsInfo()
end

function A:TALENTS_INFO(payload, sender)
    local talents = { strsplit(",", payload) }
    if C.guildRoster[sender] then
        local class = select(11, unpack(C.guildRoster[sender]))
        local tmp = {}
        local amounts = {}
        local spec
        local total = 0
        for _, v in ipairs(talents) do
            local name, numTalents = strsplit("-", v)
            local icon = self.TALENTS[class][name]
            local amount = tonumber(numTalents)
            local data = {name = name, icon = icon, amount = amount}
            table.insert(tmp, data)
            table.insert(amounts, amount)
            total = total + amount
            if not spec or spec.amount < amount then
                spec = data
            end
        end
        if total > 0 then
            Talents[sender] = {tmp, spec, amounts}
        end
    end
end

function A:CHARACTER_POINTS_CHANGED()
    E:ShareTalents(sender)
end

function A:TALENTS_INFO_REQUEST(sender)
    E:ShareTalents(sender)
end

function A:GUILD_MEMBER_COUNT_CHANGED(_, online)
    for player, _ in pairs(online) do
        E:RequestTalentsInfoFrom(player)
    end
end

function A:UPDATE_GUILD_MEMBER(row, index)
    E:UpdateTalentsInfo(index, row)
end

function A:ADDON_LOADED(name)
    --if name == "Blizzard_InspectUI" then
    --    print("LOADED INSPECT")
    --    InspectFrame:Show()
    --end
end
