---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by brode.
--- DateTime: 07.02.2022 22:55
---

local AddonName, E = ...

Bohemian.RegisterModule(AddonName, E, function()
    E:CreateGuildFrameTalentsButtons()
end)
local C = E.CORE

if not Talents then
    Talents = {}
end

E.EVENT = {
    TALENTS_INFO = "TALENTS_INFO",
    TALENTS_INFO_REQUEST = "TALENTS_INFO_REQUEST",
}

function E:ShareTalents(sendTo)
    local numTabs = GetNumTalentTabs();
    local tabs = {}
    for t = 1, numTabs do
        local name, _, pointsSpent = GetTalentTabInfo(t)
        table.insert(tabs, name:gsub("%s+", "") .. "-" .. pointsSpent)
    end
    local payload = table.concat(tabs, ",")
    if sendTo then
        C:SendEventTo(sendTo, self.EVENT.TALENTS_INFO, payload)
    else
        C:SendEvent("GUILD", self.EVENT.TALENTS_INFO, payload)
    end
end

function E:GetPlayerTalents(fullName)
    if Talents[fullName] then
        return unpack(Talents[fullName])
    end
end

function E:RequestTalentsInfo()
    C:SendEvent("GUILD", self.EVENT.TALENTS_INFO_REQUEST)
end

function E:RequestTalentsInfoFrom(player)
    C:SendEventTo(player, self.EVENT.TALENTS_INFO_REQUEST)
end
