---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by brode.
--- DateTime: 10.02.2022 10:15
---

local _, E = ...

function E:HookLootFrame()
    for i = 1, 4 do
        E:HookLootItemFrame(_G["LootButton"..i], i)
    end
    for i = 1, 11 do
        local n = 1
        while true do
            local itemFrame = _G["ContainerFrame"..i.."Item"..n]
            if not itemFrame then
                break
            end
            E:HookContainerItemFrame(itemFrame)
            n = n + 1
        end

    end
end

function E:HookLootItemFrame(frame, index)
    frame:HookScript("OnClick", function()
        if (E:CanStartAuctionWithClick()) then
            local numLootItems = GetNumLootItems()
            local numLootToShow = LOOTFRAME_NUMBUTTONS;
            if ( numLootItems > LOOTFRAME_NUMBUTTONS ) then
                numLootToShow = numLootToShow - 1; -- make space for the page buttons
            end
            local slot = (numLootToShow * (LootFrame.page - 1)) + index;
            E:StartAuctionFromLoot(slot, frame)
        end
    end)
end

function E:StartAuctionFromLoot(slot, frame)
    local texture, item, quantity, currencyID, quality, _, _, _, _ = GetLootSlotInfo(slot);
    if ( currencyID ) then
        item, texture, quantity, quality = CurrencyContainerUtil.GetCurrencyContainerInfo(currencyID, quantity, item, texture, quality);
    end

    local itemLink = GetLootSlotLink(slot)
    E:StartAuction(itemLink, quantity, frame)
end


function E:HookContainerItemFrame(frame)
    frame:HookScript("OnClick", function(self)
        if (E:CanStartAuctionWithClick()) then
	        local containerItemInfoTable = C_Container.GetContainerItemInfo(self:GetParent():GetID(), self:GetID());
	        E:StartAuction(containerItemInfoTable.hyperlink, containerItemInfoTable.stackCount, frame)
        end
    end)
end

function E:HookAdiBags()
    local i = 1
    while true do
        local adiBagsFrame = _G["AdiBagsItemButton" .. i]
        if not adiBagsFrame then
            return
        end
        E:HookContainerItemFrame(adiBagsFrame)
        i = i + 1
    end
end

local hookedFrames = {}
function E:HookXLoot()
    local i = 1
    while true do
        local frame = _G["XLootFrameButton" .. i]

        if not frame then
            return
        end
        if not hookedFrames[frame] then
            hookedFrames[frame] = true
            E:HookXLootFrame(frame, i)
        end

        i = i + 1
    end
end

function E:HookXLootFrame(frame, index)
    frame:HookScript("OnClick", function()
        if (E:CanStartAuctionWithClick()) then
            E:StartAuctionFromLoot(index, frame.frame_item)
        end
    end)
end
